name: project
services:
  app:
    image: gimaevra94/app:latest
    container_name: app
    hostname: app
    ports:
      - 8000:8000
    profiles: [dev]
    networks:
      - net

  db:
    image: gimaevra94/db:latest
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - db:/db
    ports: 
      - 3306:3306
    profiles:
      - dev
    networks:
      - net

volumes:
  db:

networks:
  net:
    driver: bridge